config/routes.rb
Rails.application.routes.draw do
  

  

  

  # get 'welcome/index'

  resources :add_voter_reasons
  # get 'verification_page/index'

  devise_for :users
  # devise_for :models
  resources :roles
  resources :vote_results
  resources :voter_tokens
  resources :registered_voters
  resources :candidate_masters
  resources :portfolio_masters
  resources :program_masters
  resources :gender_masters
  resources :department_masters
  resources :faculty_masters
  resources :session_masters
  resources :level_masters
  
 # root to: 'home#index'
 root to: 'welcome#welcome'
 
 # admin home page
 get '/home/index' => 'home#index', :as => 'admin_home'
 
 # voter home page
 get 'vote_cast_page/voter_valid' => 'vote_cast_page#voter_valid', :as => 'voter_page'
 
 # verification page
  get '/verification_page/index' => 'verification_page#index', :as => 'verification_page'
  
  # polling agents page
  get '/polling_agent_page/index' => 'polling_agent_page#index', :as => 'polling_agent'
  
  # verify voter
  get 'verify_voter'   =>  'verification_page#verify_voter'
  
  # Display token
  get 'token_show'   =>  'verification_page#token_show'
  
  
   # validate voter
  get 'validate_voter'   =>  'vote_cast_page#validate_voter'
  
  # vote pages
 
  get 'vote_page/president' => 'vote_page#president', :as => 'president_page'
  get 'vote_page/secretary' => 'vote_page#secretary', :as => 'secretary_page'
  get 'vote_page/treasurer' => 'vote_page#treasurer', :as => 'treasurer_page'
  get 'vote_page/finacial_secretary' => 'vote_page#finacial_secretary', :as => 'finacial_secretary_page'
  get 'vote_page/wocom' => 'vote_page#wocom', :as => 'wocom_page' 
  
  
 devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
 
   
 # Enable and disable faculty
 get       'enable_faculty'    =>  'faculty_masters#enable_faculty'
 get       'disable_faculty'   =>  'faculty_masters#disable_faculty'
 
 # Enable and disable department
 get       'enable_department'   =>  'department_masters#enable_department'
 get       'disable_department'   =>  'department_masters#disable_department'
 
 # Enable and disable program
 get       'enable_program'   =>  'program_masters#enable_program'
 get       'disable_program'   =>  'program_masters#disable_program'
 
 # Enable and disable portfolio
 get       'enable_portfolio'   =>  'portfolio_masters#enable_portfolio'
 get       'disable_portfolio'   =>  'portfolio_masters#disable_portfolio'
 
  # Enable and disable session
 get       'enable_session'   =>  'session_masters#enable_session'
 get       'disable_session'   =>  'session_masters#disable_session'
 
  # Enable and disable level
 get       'enable_level'   =>  'level_masters#enable_level'
 get       'disable_level'   =>  'level_masters#disable_level'
 
  # Enable and disable voter
 get       'enable_voter'   =>  'registered_voters#enable_voter'
 get       'disable_voter'   =>  'registered_voters#disable_voter'
 
 # Enable and disable candidate
 get       'enable_candidate_prez'   =>  'candidate_masters#enable_candidate_prez'
 get       'disable_candidate_prez'   =>  'candidate_masters#disable_candidate_prez'
 
 get       'enable_candidate_sec'   =>  'candidate_masters#enable_candidate_sec'
 get       'disable_candidate_sec'   =>  'candidate_masters#disable_candidate_sec'
 
 get       'enable_candidate_tr'   =>  'candidate_masters#enable_candidate_tr'
 get       'disable_candidate_tr'   =>  'candidate_masters#disable_candidate_tr'
 
 get       'enable_candidate_f_sec'   =>  'candidate_masters#enable_candidate_f_sec'
 get       'disable_candidate_f_sec'   =>  'candidate_masters#disable_candidate_f_sec'
 
 get       'enable_candidate_wocom'   =>  'candidate_masters#enable_candidate_wocom'
 get       'disable_candidate_wocom'   =>  'candidate_masters#disable_candidate_wocom'
 
 
 
 
 
 # Enable and disable user
 get       'enable_user'   =>  'users#enable_user'
 get       'disable_user'   =>  'users#disable_user'
 
  # Enable and disable role
 get       'enable_role'   =>  'roles#enable_role'
 get       'disable_role'   =>  'roles#disable_role'
 
 
 post 'submit_vote_result' => 'vote_page#submit_vote_result'
 
 
  
 # Download excel and cvs for faculty
 get 'all_faculty_excel' => 'faculty_masters#all_faculty_excel'
 
 # Download excel and cvs for department
 get 'all_department_excel' => 'department_masters#all_department_excel'
 
 # Download excel and cvs for programs
 get 'all_program_excel' => 'program_masters#all_program_excel'
 
 # Download excel and cvs for portfolios
 get 'all_portfolio_excel' => 'portfolio_masters#all_portfolio_excel'
 
 # Download excel and cvs for session
 get 'all_session_excel' => 'session_masters#all_session_excel'
 
  # Download excel and cvs for level
 get 'all_level_excel' => 'level_masters#all_level_excel'
 
 # Download excel and cvs for voters
 get 'all_voter_excel' => 'registered_voters#all_voter_excel'
 
 # Download excel and cvs for candidates
 get 'all_candidate_excel' => 'candidate_masters#all_candidate_excel'
 
  # Download excel and cvs for users
 get 'all_users_excel' => 'users#all_users_excel'
 
  # Download excel and cvs for roles
 get 'all_roles_excel' => 'roles#all_roles_excel'
 
 
 # filtering tabbed candidates
 get 'president' => 'candidate_masters#president'
 get 'secretary' => 'candidate_masters#secretary'
 get 'treasurer' => 'candidate_masters#treasurer'
 get 'finance_sec' => 'candidate_masters#finance_sec'
 get 'wocom' => 'candidate_masters#wocom'
  
end

app/controllers/candidate_masters_controller.rb
class CandidateMastersController < ApplicationController
  before_action :set_candidate_master, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /candidate_masters
  # GET /candidate_masters.json
  def index
    @candidate_prez = CandidateMaster.where(portfolio_id: "P", active_status: true).paginate(:page => params[:page], :per_page => 3).order('slot_id asc')
    @candidate_sec = CandidateMaster.where(portfolio_id: "S", active_status: true).paginate(:page => params[:page], :per_page => 3).order('slot_id asc')
    @candidate_tr = CandidateMaster.where(portfolio_id: "TR", active_status: true).paginate(:page => params[:page], :per_page => 3).order('slot_id asc')
    @candidate_f_sec = CandidateMaster.where(portfolio_id: "FS", active_status: true).paginate(:page => params[:page], :per_page => 3).order('slot_id asc')
    @candidate_wocom = CandidateMaster.where(portfolio_id: "WC", active_status: true).paginate(:page => params[:page], :per_page => 3).order('slot_id asc')
     
   
    # if params[:count]
      # params[:count]
   # else
     # params[:count] = 5
   # end
#    
   # if params[:page]
     # page = params[:page].to_i
   # else
     # page = 1
   # end
#    
   # if params[:per_page].present?
      # # perpage = params[:per_page]
      # @per_page = params[:per_page] || CandidateMaster.per_page || 5
      # @candidate_masters = CandidateMaster.paginate( :per_page => @per_page, :page => params[:page])
   # else
     # perpage = 5
   # end
   # @per_page = params[:per_page] || CandidateMaster.per_page || 5
   # page = if params[:page]
            # params[:page].to_i
           # else
            # 1
           # end
#    
#    
# #            
   # # per_page = 5
# #    
   # # offset = (page - 1) * per_page
   # # limit = page * per_page
   # # @array = *(offset...limit)
# 
# 
   # if  params[:search_value] && params[:search_value].strip != ''
#      
     # if params[:search_param] == 'portfolio'
       # logger.info "the code comes to if  portfolio............"
       # @candidate_masters = CandidateMaster.portfolio_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
#        
      # # elsif params[:search_param] == 'program_name'
        # # logger.info "the code comes to elsif program name............."
         # # @candidate_masters = CandidateMaster.program_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
# #          
      # # elsif params[:search_param] == 'session'
        # # logger.info "the code comes to elsif session............."
         # # @candidate_masters = CandidateMaster.session_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
# #      
# #      
      # # elsif params[:search_param] == 'level'
        # # logger.info "the code comes to elsif level............."
         # # @candidate_masters = CandidateMaster.level_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
# #         
     # else
       # logger.info "the code comes to the else...."
        # @candidate_masters = CandidateMaster.paginate(page: params[:page], per_page: params[:count]).order('created_at desc')
        # @search_json = []
     # end
#     
    # elsif params[:search_param] == 'date'
       # logger.info "the code comes to elsif date............."
#        
       # start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
       # ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
       # @candidate_masters = CandidateMaster.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
#  
#      
   # end
   # p "JSON ARRAY: #{@search_json}"
# #     
#     
    respond_to do |format|
      logger.info "what is the url calling this??: ans #{request.referer}"
      format.js
      format.html
      format.csv { send_data @candidate_masters.to_csv(options = {}, page, perpage)}
      format.xls { send_data @candidate_masters.to_csv(options={col_sep: "\t"}, page, perpage)}
    end
    
  end

  
  # Presidents
  def president
     @candidate_prez = CandidateMaster.where(portfolio_id: "P").paginate(:page => params[:page], :per_page => 3).order('slot_id asc')
    
   
    if params[:count]
      params[:count]
   else
     params[:count] = 5
   end
   
   if params[:page]
     page = params[:page].to_i
   else
     page = 1
   end
   
   if params[:per_page].present?
      # perpage = params[:per_page]
      @per_page = params[:per_page] || CandidateMaster.where(portfolio_id: "P").per_page || 5
      @candidate_prez = CandidateMaster.where(portfolio_id: "P").paginate( :per_page => @per_page, :page => params[:page]).order('slot_id asc')
   else
     perpage = 5
   end
   @per_page = params[:per_page] || CandidateMaster.where(portfolio_id: "P").per_page || 5
   page = if params[:page]
            params[:page].to_i
           else
            1
           end
 
   if  params[:search_value] && params[:search_value].strip != ''
     
     if params[:search_param] == 'candidate_id'
       logger.info "the code comes to if  candidate id............"
       @candidate_prez = CandidateMaster.where(portfolio_id: "P").candidate_id_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('slot_id asc')
       
      # elsif params[:search_param] == 'program_name'
        # logger.info "the code comes to elsif program name............."
         # @candidate_masters = CandidateMaster.program_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
#          
      # elsif params[:search_param] == 'session'
        # logger.info "the code comes to elsif session............."
         # @candidate_masters = CandidateMaster.session_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
#      
#      
      # elsif params[:search_param] == 'level'
        # logger.info "the code comes to elsif level............."
         # @candidate_masters = CandidateMaster.level_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
#         
     else
       logger.info "the code comes to the else...."
        @candidate_prez = CandidateMaster.where(portfolio_id: "P").paginate(page: params[:page], per_page: params[:count]).order('slot_id asc')
        @search_json = []
     end
    
    elsif params[:search_param] == 'date'
       logger.info "the code comes to elsif date............."
       
       start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
       ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
       @candidate_prez = CandidateMaster.where(portfolio_id: "P").search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('slot_id asc')
 
     
   end
   p "JSON ARRAY: #{@search_json}" 
#     
    
    respond_to do |format|
      logger.info "what is the url calling this??: ans #{request.referer}"
      format.js
      format.html
      format.csv { send_data @candidate_masters.to_csv(options = {}, page, perpage)}
      format.xls { send_data @candidate_masters.to_csv(options={col_sep: "\t"}, page, perpage)}
    end
    
  end

  def secretary
    @candidate_sec = CandidateMaster.where(portfolio_id: "S").paginate(:page => params[:page], :per_page => 3).order('slot_id asc')
    
   
    if params[:count]
      params[:count]
   else
     params[:count] = 3
   end
   
   if params[:page]
     page = params[:page].to_i
   else
     page = 1
   end
   
   if params[:per_page].present?
      # perpage = params[:per_page]
      @per_page = params[:per_page] || CandidateMaster.where(portfolio_id: "P").per_page || 3
      @candidate_sec = CandidateMaster.where(portfolio_id: "S").paginate( :per_page => @per_page, :page => params[:page]).order('slot_id asc')
   else
     perpage = 3
   end
   @per_page = params[:per_page] || CandidateMaster.where(portfolio_id: "S").per_page || 3
   page = if params[:page]
            params[:page].to_i
           else
            1
           end
 
   if  params[:search_value] && params[:search_value].strip != ''
     
     if params[:search_param] == 'candidate_sec'
       logger.info "the code comes to if  candidate sec............"
       @candidate_sec = CandidateMaster.where(portfolio_id: "S").candidate_id_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('slot_id asc')
       
      # elsif params[:search_param] == 'program_name'
        # logger.info "the code comes to elsif program name............."
         # @candidate_masters = CandidateMaster.program_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
#          
      # elsif params[:search_param] == 'session'
        # logger.info "the code comes to elsif session............."
         # @candidate_masters = CandidateMaster.session_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
#      
#      
      # elsif params[:search_param] == 'level'
        # logger.info "the code comes to elsif level............."
         # @candidate_masters = CandidateMaster.level_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')

app/helpers/candidate_masters_helper.rb
module CandidateMastersHelper
end

app/views/candidate_masters/_presidents.html.erb
<div class="container" id = "page-container" >
<!-- <h4>Candidates</h4> -->
<p style = 'text-align: center; font-family: tahoma; font-size: 15px;'>
  	<b>Download All Candidates:</b>  
        <%= link_to "CSV", all_candidate_excel_path(format: "csv"), :class => "w3-hover-white", method: :get%> 
      | <%= link_to "Excel", all_candidate_excel_path(format: "xls"),:class => "w3-hover-white", method: :get%>
</p>
<% if flash[:notice] %>
   <p class="flash_notice" id = 'notes' style = "margin-top: 5px"><%= notice %></p>
<% end %>	
	
	<div class="pull-left" style = 'margin-top: %;'>
	   <%= form_tag president_path, method: :get, remote: true, input_html:{display:"block"} do %>
			<div class="radio_div"> 
			   <b>Filter By:</b><br />
			   <input id="candidate_id" type="radio" name="search_param" value="candidate_id" class = "w3-radio" /> Candidate ID
			   <!-- <input id="program_name" type="radio" name="search_param" value="program_name" class = "w3-radio" /> Program
		       <input id="session" type="radio" name="search_param" value="session" class = "w3-radio" /> Session
		       <input  id="level" type="radio" name="search_param" value="level" class = "w3-radio" /> Level -->
		       
			   <input id="date" type="radio" name="search_param" value="date" class = "w3-radio" /> Date  
			</div>
					
										
			<div class="form-inline" style = 'margin-top: 5px; margin-bottom: '>
				<input id="search-field" class="hidden w3-input w3-border w3-round form-control"  name="search_value" />
				<input type="submit" id="search-field2" class=" hidden w3-button w3-blue w3-round-xxlarge w3-small" value="Search"  >
			</div>
					
			<div id="date_div" class="form-inline" style ="margin-top: 5px; margin-bottom:">
		         <input type="text" class="hidden w3-input w3-border w3-round form-control" data-provide='datepicker' name="start_date" id="date-field" placeholder="Start date "/>
		         <span class="add-on hidden" id = 'to'> to </span>
		                
		         <input type="text" class="hidden w3-input w3-border w3-round form-control" data-provide='datepicker' name="end_date" id="date-field2" placeholder="End date "/>
		               
		         <input type="submit" id="search-field3" class=" hidden w3-button w3-blue w3-round-xxlarge w3-small" value="Search" style = "margin-left: 5px;" >
	  
	       </div>
	      
	                
	    <% end %>
	   
	</div>
	
	 <div class="pull-right" style = 'margin-top: %; '>
	  <label class="">Display <u>No</u>: </label>  
	   <%= select_tag :per_page, options_for_select([3,4, 5, 6, 7, 10, 100], params[:per_page].to_i), :data => { :remote => true, 
	 	            :url => url_for( :controller => "candidate_masters", :action => "president" )
	 	             }, remote: true, class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4 w3-white" %>	
     </div>
     <div class="clearfix"></div>
	<br />



<div class="table-responsive" id="table">
	<table class="table table-condensed table-bordered table-striped w3-card">
	  <thead>
	    <tr class="w3-pale-blue">
	      <th>Slot</th>
	      <th>Profile Image</th>
	      <th>Candidate ID</th>
	      <th>Candidate Name</th>
     	  <th>Portfolio</th>	      
	      <th>Status</th>
	      <th colspan="2">Options</th>
	    </tr> 
	  </thead>
	
	  <tbody>
	    <% @candidate_prez.each do |candidate_prez| %>
	      <tr>
	      	<td><%= candidate_prez.slot_id %></td>
	      	<td style="width: 10%">
	      		<% if candidate_prez.image.present?%>
	      		  <%= image_tag candidate_prez.image.url(:thumb), class: "img-thumbnail ", style: "width: 100px;  margin: 2px" %>	      		  
	      		<%else%>
	      		  <%= image_tag ('user.png'), class: "img-thumbnail", style: "width: 100px;  margin: 2px" %> 
	      		<%end%>
	      	</td>
	        <td><%= candidate_prez.candidate_id %></td>
	        <td><%= candidate_prez.registered_voter.surname %> <%= candidate_prez.registered_voter.other_names %></td>
	        <td><%= candidate_prez.portfolio_master.portfolio %></td>
	        <% if candidate_prez.active_status == true %>  
	            <td style="color: ">Active</td>	      		 
	        <%elsif candidate_prez.active_status == false %>
	            <td style="color: red">Inactive</td>	      		
	        <%end%>
	        
	        <td style="width: 10px">
		        <%= link_to  edit_candidate_master_path(candidate_prez), class: "w3-btn w3-sand w3-card  w3-tiny w3-round w3-round-xxlarge " do %>
				    <i class="fa fa-edit fa-2x" style="color: blue" aria-hidden="true" title="Edit Faculty"> </i>  
			    <% end %> 		        	
		    </td>
		    
		    <td style="width: 10px">
			    <% if candidate_prez.active_status == false %>
			       		<%= link_to  enable_candidate_prez_path(:chosen => candidate_prez.id), remote: true, :title =>"", class: "w3-btn w3-sand w3-card  w3-tiny w3-round w3-round-xxlarge ", data: { confirm: 'You are about to restore the selected candidate. Do you want to continue?' } do %>
						  <i class="fa fa-check fa-2x" style="color: green" aria-hidden="true" title="Restore Department"> </i>  
						<% end %> 
			       
		        <% else candidate_prez.active_status == true %>
		           		<%= link_to  disable_candidate_prez_path(:chosen => candidate_prez.id),remote: true,  class: "w3-btn w3-sand w3-card  w3-tiny w3-round w3-round-xxlarge ", data: { confirm: 'You are about to delete the selected candidate. Do you want to continue?' } do %>
						  <i class="fa fa-trash-o fa-2x" style="color: red" aria-hidden="true" title="Delete Department"> </i>  
		                <% end %>		          
		        <% end %>	
	        </td>

	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>
<br>

<%= link_to '+', new_candidate_master_path, class: "w3-button w3-circle w3-light-blue w3-hover-pale-blue" %>
<%= will_paginate @candidate_prez,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "candidate_masters", :action => "president", count: params[:count], page: params[:page] }  %>
</div>
<br />

<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 });
 
</script>

<script>
  $(function(){
    $('.pagination a').attr('data-remote', 'true')
  });

</script>


<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        
        // filter by portfolio
        $("#candidate_id").click(function() {
            if ($("#candidate_id").is(":checked")) {
                $("#search-field").attr("placeholder", "Enter candidate id");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
                $("#date-field").addClass("hidden");
                $("#date-field2").addClass("hidden");
                $("#search-field3").addClass("hidden")
                $("#to").addClass("hidden");
            }
        });
        
        // filter by voter
        // $("#voter_id").click(function() {
            // if ($("#voter_id").is(":checked")) {
                // $("#search-field").attr("placeholder", "Enter the voter id number");
                // $("#search-field2").removeClass("hidden");
                // $("#search-field").removeClass("hidden");
                // $("#date-field").addClass("hidden");
                // $("#date-field2").addClass("hidden");
                // $("#search-field3").addClass("hidden")
                // $("#to").addClass("hidden");
            // }
        // });
//         
//         
        // // filter by session
        // $("#session").click(function() {
            // if ($("#session").is(":checked")) {
                // $("#search-field").attr("placeholder", "Enter the session");
                // $("#search-field2").removeClass("hidden");
                // $("#search-field").removeClass("hidden");
                // $("#date-field").addClass("hidden");
                // $("#date-field2").addClass("hidden");
                // $("#search-field3").addClass("hidden")
                // $("#to").addClass("hidden");
            // }
        // });
//         
//         
        // // filter by level
        // $("#level").click(function() {
            // if ($("#level").is(":checked")) {
                // $("#search-field").attr("placeholder", "Enter the level");
                // $("#search-field2").removeClass("hidden");
                // $("#search-field").removeClass("hidden");
                // $("#date-field").addClass("hidden");
                // $("#date-field2").addClass("hidden");
                // $("#search-field3").addClass("hidden")
                // $("#to").addClass("hidden");
            // }
        // });
//         
       
      
        
        ////////////////////////////////////////////////////////////////////////////
        $("#location").click(function() {
            if ($("#location").is(":checked")) {
                $("#search-field").attr("placeholder", "Enter the location");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        
        
         //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").addClass("hidden");
            $("#search-field").addClass("hidden");
            $("#search-field3").removeClass("hidden");
            $("#to").removeClass("hidden");
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        $("#date-field").click(function() {
           // if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            // $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        
        ///////////////////////////////////////////////////
        $.fn.datepicker.noConflict = function() {
            $.fn.datepicker = old;
            return this;
        };
        ////////////////////////////////////////////////////
        $(function() {
            $('#date-field').datepicker({
                dateFormat : 'yy-mm-dd'
            }).val();
        });
        //////////////////////////////////////////////////////
        $(function() {
            $('#date-field2').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
        
        
        
     
        // ///////////////////////////////////////////////////
        // $.fn.datepicker.noConflict = function() {
            // $.fn.datepicker = old;
            // return this;
        // };
        // ////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
        // //////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field2').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
//         
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

app/views/candidate_masters/disable_candidate_f_sec.js.erb
$("#F_Secretary").html("<%= escape_javascript(render(:partial=>"f_secretaries")) %>");

app/views/candidate_masters/disable_candidate_prez.js.erb
$("#President").html("<%= escape_javascript(render(:partial=>"presidents")) %>");