config/routes.rb
Rails.application.routes.draw do
  

  

  

  # get 'welcome/index'

  resources :add_voter_reasons
  # get 'verification_page/index'

  devise_for :users
  # devise_for :models
  resources :roles
  resources :vote_results
  resources :voter_tokens
  resources :registered_voters
  resources :candidate_masters
  resources :portfolio_masters
  resources :program_masters
  resources :gender_masters
  resources :department_masters
  resources :faculty_masters
  resources :session_masters
  resources :level_masters
  
 # root to: 'home#index'
 root to: 'welcome#welcome'
 
 # admin home page
 get '/home/index' => 'home#index', :as => 'admin_home'
 
 # voter home page
 get 'vote_cast_page/voter_valid' => 'vote_cast_page#voter_valid', :as => 'voter_page'
 
 # verification page
  get '/verification_page/index' => 'verification_page#index', :as => 'verification_page'
  
  # polling agents page
  get '/polling_agent_page/index' => 'polling_agent_page#index', :as => 'polling_agent'
  
  # verify voter
  get 'verify_voter'   =>  'verification_page#verify_voter'
  
  # Display token
  get 'token_show'   =>  'verification_page#token_show'
  
  
   # validate voter
  get 'validate_voter'   =>  'vote_cast_page#validate_voter'
  
  # vote pages
 
  get 'vote_page/president' => 'vote_page#president', :as => 'president_page'
  get 'vote_page/secretary' => 'vote_page#secretary', :as => 'secretary_page'
  get 'vote_page/treasurer' => 'vote_page#treasurer', :as => 'treasurer_page'
  get 'vote_page/finacial_secretary' => 'vote_page#finacial_secretary', :as => 'finacial_secretary_page'
  get 'vote_page/wocom' => 'vote_page#wocom', :as => 'wocom_page' 
  
  
 devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
 
   
 # Enable and disable faculty
 get       'enable_faculty'    =>  'faculty_masters#enable_faculty'
 get       'disable_faculty'   =>  'faculty_masters#disable_faculty'
 
 # Enable and disable department
 get       'enable_department'   =>  'department_masters#enable_department'
 get       'disable_department'   =>  'department_masters#disable_department'
 
 # Enable and disable program
 get       'enable_program'   =>  'program_masters#enable_program'
 get       'disable_program'   =>  'program_masters#disable_program'
 
 # Enable and disable portfolio
 get       'enable_portfolio'   =>  'portfolio_masters#enable_portfolio'
 get       'disable_portfolio'   =>  'portfolio_masters#disable_portfolio'
 
  # Enable and disable session
 get       'enable_session'   =>  'session_masters#enable_session'
 get       'disable_session'   =>  'session_masters#disable_session'
 
  # Enable and disable level
 get       'enable_level'   =>  'level_masters#enable_level'
 get       'disable_level'   =>  'level_masters#disable_level'
 
  # Enable and disable voter
 get       'enable_voter'   =>  'registered_voters#enable_voter'
 get       'disable_voter'   =>  'registered_voters#disable_voter'
 
 # Enable and disable candidate
 get       'enable_candidate_prez'   =>  'candidate_masters#enable_candidate_prez'
 get       'disable_candidate_prez'   =>  'candidate_masters#disable_candidate_prez'
 
 get       'enable_candidate_sec'   =>  'candidate_masters#enable_candidate_sec'
 get       'disable_candidate_sec'   =>  'candidate_masters#disable_candidate_sec'
 
 get       'enable_candidate_tr'   =>  'candidate_masters#enable_candidate_tr'
 get       'disable_candidate_tr'   =>  'candidate_masters#disable_candidate_tr'
 
 get       'enable_candidate_f_sec'   =>  'candidate_masters#enable_candidate_f_sec'
 get       'disable_candidate_f_sec'   =>  'candidate_masters#disable_candidate_f_sec'
 
 get       'enable_candidate_wocom'   =>  'candidate_masters#enable_candidate_wocom'
 get       'disable_candidate_wocom'   =>  'candidate_masters#disable_candidate_wocom'
 
 
 
 
 
 # Enable and disable user
 get       'enable_user'   =>  'users#enable_user'
 get       'disable_user'   =>  'users#disable_user'
 
  # Enable and disable role
 get       'enable_role'   =>  'roles#enable_role'
 get       'disable_role'   =>  'roles#disable_role'
 
 
 post 'submit_vote_result' => 'vote_page#submit_vote_result'
 
 
  
 # Download excel and cvs for faculty
 get 'all_faculty_excel' => 'faculty_masters#all_faculty_excel'
 
 # Download excel and cvs for department
 get 'all_department_excel' => 'department_masters#all_department_excel'
 
 # Download excel and cvs for programs
 get 'all_program_excel' => 'program_masters#all_program_excel'
 
 # Download excel and cvs for portfolios
 get 'all_portfolio_excel' => 'portfolio_masters#all_portfolio_excel'
 
 # Download excel and cvs for session
 get 'all_session_excel' => 'session_masters#all_session_excel'
 
  # Download excel and cvs for level
 get 'all_level_excel' => 'level_masters#all_level_excel'
 
 # Download excel and cvs for voters
 get 'all_voter_excel' => 'registered_voters#all_voter_excel'
 
 # Download excel and cvs for candidates
 get 'all_candidate_excel' => 'candidate_masters#all_candidate_excel'
 
  # Download excel and cvs for users
 get 'all_users_excel' => 'users#all_users_excel'
 
  # Download excel and cvs for roles
 get 'all_roles_excel' => 'roles#all_roles_excel'
 
 
 # filtering tabbed candidates
 get 'president' => 'candidate_masters#president'
 get 'secretary' => 'candidate_masters#secretary'
 get 'treasurer' => 'candidate_masters#treasurer'
 get 'finance_sec' => 'candidate_masters#finance_sec'
 get 'wocom' => 'candidate_masters#wocom'
  
end

app/models/department_master.rb
class DepartmentMaster < ActiveRecord::Base
    validates :department_name, presence: {message: "Please enter a department name"}
    validates :faculty_id, presence: {message: "Please select a faculty"}
    before_save :titler
  
   belongs_to :faculty_master, class_name: 'FacultyMaster', foreign_key: :faculty_id 
   has_many :program_masters, foreign_key: :department_id
  
   def titler
      str_list = self.department_name.split
  
      self.department_name  = str_list.map { |word| word.capitalize
      word.split("-").map{|w| w.capitalize }.join("-")
      }.join(" ")
   end
   
    # filter by department
  def self.department_search(department)   
      department = "%#{department}%"
      where('department_name LIKE ?', department) 
  end
  
  # filter by faculty
  def self.faculty_search(faculty)   
      faculty = "%#{faculty}%"
      joins(:faculty_master).where('faculty_masters.faculty_name LIKE ?', faculty) 
  end
  
  
  # filter by date
  def self.search_date(start = nil, ended = nil)
    if start && ended
      where(created_at: "#{start}".."#{ended}")
    else
      all
    end
  end
  
  
  def self.to_csv(options = {}, page=nil, perpage=nil)
        column_names = %w{department_name faculty active_status created_at }

        if page and perpage

            page = page.to_i
            perpage= perpage.to_i

            off = perpage*(page - 1)
 
            CSV.generate(options) do |csv|
                csv << column_names
               limit(perpage).offset(off).each do |request|
                    csv << request.attributes.values_at(*column_names)
                end
            end

        else
            CSV.generate(options) do |csv|
                csv << column_names
                 all.each do |request|
                 
                 row = request.attributes.values_at(*column_names) 
                 row[1]= request.faculty_master.faculty_name
                 row[2] = request.active_status ? 'Active' : 'Inactive'
                 csv << row
                end
            end
        end

    end
   
   
  
end

app/controllers/department_masters_controller.rb
class DepartmentMastersController < ApplicationController
  before_action :set_department_master, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /department_masters
  # GET /department_masters.json
  def index
    @department_masters = DepartmentMaster.where(active_status: true).paginate(:page => params[:page], :per_page => 10)
    
    if params[:count]
      params[:count]
   else
     params[:count] = 10
   end
   
   if params[:page]
     page = params[:page].to_i
   else
     page = 1
   end
   
   if params[:per_page].present?
      # perpage = params[:per_page]
      @per_page = params[:per_page] || DepartmentMaster.per_page || 10
      @department_masters = DepartmentMaster.paginate( :per_page => @per_page, :page => params[:page])
   else
     perpage = 10
   end
   @per_page = params[:per_page] || DepartmentMaster.per_page || 10
   page = if params[:page]
            params[:page].to_i
           else
            1
           end
   
   
#            
   # per_page = 5
#    
   # offset = (page - 1) * per_page
   # limit = page * per_page
   # @array = *(offset...limit)


   if  params[:search_value] && params[:search_value].strip != ''
     
     if params[:search_param] == 'department_name'
       logger.info "the code comes to if  department name............"
       @department_masters = DepartmentMaster.department_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
       
      elsif params[:search_param] == 'faculty_name'
        logger.info "the code comes to elsif faculty name............."
         @department_masters = DepartmentMaster.faculty_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
        
     else
       logger.info "the code comes to the else...."
        @department_masters = DepartmentMaster.paginate(page: params[:page], per_page: params[:count]).order('created_at desc')
        @search_json = []
     end
    
    elsif params[:search_param] == 'date'
       logger.info "the code comes to elsif date............."
       
       start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
       ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
       @department_masters = DepartmentMaster.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('created_at asc')
 
     
   end
   p "JSON ARRAY: #{@search_json}"
#     
    
    respond_to do |format|
      logger.info "what is the url calling this??: ans #{request.referer}"
      format.js
      format.html
      format.csv { send_data @department_masters.to_csv(options = {}, page, perpage)}
      format.xls { send_data @department_masters.to_csv(options={col_sep: "\t"}, page, perpage)}
    end
    
  end

  # GET /department_masters/1
  # GET /department_masters/1.json
  def show
  end

  # GET /department_masters/new
  def new
    @department_master = DepartmentMaster.new
  end

  # GET /department_masters/1/edit
  def edit
  end
  
  def all_department_excel
    @department_masters = DepartmentMaster.all.order('created_at desc')
    respond_to do |format|
      # format.json {render json: @search_json[1..10]}
      # p "JSON ARRAY: #{@search_json}"
      format.html
      format.js
      format.csv { send_data @department_masters.to_csv }
      format.xls { send_data @department_masters.to_csv(options={col_sep: "\t"}) }
    end
  end
  
  def enable_department
      department_id=params[:chosen]
      department = DepartmentMaster.find(department_id)
     if department.update(:active_status => 1)
       redirect_to department_masters_path, notice: 'Department was successfully enabled.'
     end
  end

  def disable_department
      department_id=params[:chosen]    
      department = DepartmentMaster.find(department_id)    
     if department.update(:active_status => 0)
       redirect_to department_masters_path, notice: 'Department was successfully disabled.'
     end
     
  end

  # POST /department_masters
  # POST /department_masters.json
  def create
    @department_master = DepartmentMaster.new(department_master_params)

    respond_to do |format|
      if @department_master.save
        format.html { redirect_to @department_master, notice: 'Department master was successfully created.' }
        format.json { render :show, status: :created, location: @department_master }
      else
        format.html { render :new }
        format.json { render json: @department_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /department_masters/1
  # PATCH/PUT /department_masters/1.json
  def update
    respond_to do |format|
      if @department_master.update(department_master_params)
        format.html { redirect_to @department_master, notice: 'Department master was successfully updated.' }
        format.json { render :show, status: :ok, location: @department_master }
      else
        format.html { render :edit }
        format.json { render json: @department_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /department_masters/1
  # DELETE /department_masters/1.json
  def destroy
    @department_master.destroy
    respond_to do |format|
      format.html { redirect_to department_masters_url, notice: 'Department master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department_master
      @department_master = DepartmentMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_master_params
      params.require(:department_master).permit(:department_name, :faculty_id, :user_id, :active_status, :del_status)
    end
end

app/helpers/department_masters_helper.rb
module DepartmentMastersHelper
end

app/views/department_masters/_edit_form.html.erb
<br>
<%= simple_form_for(@department_master) do |f| %>
  <%= f.error_notification %>

<div id="id01" class="w3-modal w3-card-4 w3-round-large" style="display: block;">
    <div class="w3-modal-content w3-animate-top w3-card-4 w3-light-gray" style="width: 33%; max-height: 80%; overflow-y: auto;">
    	<div style="max-width: 70%; text-align: center; margin-left: 15%; margin-top: 15px">
      
	    	<% if flash[:notice] %>
                <p class="flash_notice " id = 'notes' style = ""><%= notice %></p>
		  	 <% end %>
		  	
    	</div>	   
      <header class="w3-container">  
        <h4>Add a Department</h4> 
      </header>          
           <div class="w3-container" > 				 		      	
              
               <div class="form-inputs">
	                <%= f.input :department_name, label: "Department" %>
				    <%= f.input :faculty_id, label: "Faculty", collection: FacultyMaster.all, label_method: :faculty_name, value_method: :id %>
				    <%= f.input :user_id, as: :hidden %>
				    <%= f.input :active_status, as: :hidden, input_html: {value: 1} %>
				    <%= f.input :del_status, as: :hidden, input_html: {value: 0} %>
               </div>
           </div>
        <br>
      <footer class="w3-container">
       	<%= f.button :submit, class: "w3-button w3-teal w3-hover-teal w3-right w3-card-4 w3-small w3-round-xlarge", value: "Update" %>
        <%= link_to 'Back', department_masters_path, class: "w3-button w3-black w3-hover-black w3-left w3-card-4 w3-small w3-round-xlarge" %>
      <br />
      </footer>
      <% end %>
      <br />
    </div>
    <br />
</div>

<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 3000);
  });
</script>

app/views/department_masters/_form.html.erb
<br>
<%= simple_form_for(@department_master) do |f| %>
  <%= f.error_notification %>

<div id="id01" class="w3-modal w3-card-4 w3-round-large" style="display: block;">
    <div class="w3-modal-content w3-animate-top w3-card-4 w3-light-gray" style="width: 33%; max-height: 80%; overflow-y: auto;">
    	<div style="max-width: 70%; text-align: center; margin-left: 15%; margin-top: 15px">
      
	    	<% if flash[:notice] %>
                <p class="flash_notice " id = 'notes' style = ""><%= notice %></p>
		  	 <% end %>
		  	
    	</div>	   
      <header class="w3-container">  
        <h4>Add a Department</h4> 
      </header>          
           <div class="w3-container" > 				 		      	
              
               <div class="form-inputs">
	                <%= f.input :department_name, label: "Department" %>
				    <%= f.input :faculty_id, label: "Faculty", collection: FacultyMaster.all, label_method: :faculty_name, value_method: :id %>
				    <%= f.input :user_id, as: :hidden %>
				    <%= f.input :active_status, as: :hidden, input_html: {value: 1} %>
				    <%= f.input :del_status, as: :hidden, input_html: {value: 0} %>
               </div>
           </div>
        <br>
      <footer class="w3-container">
       	<%= f.button :submit, class: "w3-button w3-teal w3-hover-teal w3-right w3-card-4 w3-small w3-round-xlarge", value: "Add" %>
        <%= link_to 'Back', department_masters_path, class: "w3-button w3-black w3-hover-black w3-left w3-card-4 w3-small w3-round-xlarge" %>
      <br />
      </footer>
      <% end %>
      <br />
    </div>
    <br />
</div>

<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 3000);
  });
</script>

app/views/department_masters/edit.html.erb
<%= render 'edit_form' %>

app/views/department_masters/index.html.erb
<div class="container" id = "page-container" >
<% if flash[:notice] %>
   <p class="flash_notice" id = 'notes' style = "margin-top: 5px"><%= notice %></p>
<% end %>	

<h4>Departments</h4>

<br />
	<p style = 'text-align: center; font-family: tahoma; font-size: 15px;'>
  		 <b>Download:</b>  
                      <%= link_to "CSV", all_department_excel_path(format: "csv"), :class => "w3-hover-white", method: :get%> 
                     | <%= link_to "Excel", all_department_excel_path(format: "xls"),:class => "w3-hover-white", method: :get%>
	</p>
	
	
	<div class="pull-left" style = 'margin-top: %;'>
	   <%= form_tag department_masters_path, method: :get,  input_html:{display:"block"} do %>
			<div class="radio_div">
			   <b>Filter By:</b><br />
		       <input id="department_name" type="radio" name="search_param" value="department_name" class = "w3-radio" /> Department   
						
			    <input id="faculty_name" type="radio" name="search_param" value="faculty_name" class = "w3-radio" /> Faculty
			   
			   <!-- <input id="location" type="radio" name="search_param" value="location" class = "w3-radio" /> Location  --> 
						
			   <input id="date" type="radio" name="search_param" value="date" class = "w3-radio" /> Date  
			</div>
					
										
			<div class="form-inline" style = 'margin-top: 5px; margin-bottom: '>
				<input id="search-field" class="hidden w3-input w3-border w3-round form-control"  name="search_value" />
				<input type="submit" id="search-field2" class=" hidden w3-button w3-blue w3-round-xxlarge w3-small" value="Search"  >
			</div>
					
			<div id="date_div" class="form-inline" style ="margin-top: 5px; margin-bottom:">
		         <input type="text" class="hidden w3-input w3-border w3-round form-control" data-provide='datepicker' name="start_date" id="date-field" placeholder="Start date "/>
		         <span class="add-on hidden" id = 'to'> to </span>
		                
		         <input type="text" class="hidden w3-input w3-border w3-round form-control" data-provide='datepicker' name="end_date" id="date-field2" placeholder="End date "/>
		               
		         <input type="submit" id="search-field3" class=" hidden w3-button w3-blue w3-round-xxlarge w3-small" value="Search" style = "margin-left: 5px;" >
	  
	       </div>
	      
	                
	    <% end %>
	   
	</div>
	
	 <div class="pull-right" style = 'margin-top: %; '>
	  <label class="">Display <u>No</u>: </label>  
	   <%= select_tag :per_page, options_for_select([10, 20, 30, 40,50, 70,100], params[:per_page].to_i), :data => { :remote => true, 
	 	            :url => url_for( :controller => "department_masters", :action => "index" )
	 	             }, :onchange => "if(this.value){window.location='?per_page='+this.value;}", class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4 w3-white" %>	
     </div>
     <div class="clearfix"></div>
	<br />



<div class="table-responsive" id="table">
	<table class="table table-condensed table-bordered table-striped w3-card">
	  <thead>
	    <tr class="w3-pale-blue">
	      <th>S/N</th>
	      <th>Department Name</th>
	      <th>Faculty</th>
	      <th>Status</th>
	      <th colspan="2">Options</th>
	    </tr> 
	  </thead>
	
	  <tbody>
	    <% @department_masters.each_with_index do |department_master, index| %>
	      <tr>
	      	<td><%= index+1 %></td>
	        <td><%= department_master.department_name %></td>
	        <td><%= department_master.faculty_master.faculty_name %></td>
	        <% if department_master.active_status == true %>  
	            <td style="color: ">Active</td>	      		 
	        <%elsif department_master.active_status == false %>
	            <td style="color: red">Inactive</td>	      		
	        <%end%>
	        
	        <td style="width: 10px">
		        <%= link_to  edit_department_master_path(department_master), class: "w3-btn w3-sand w3-card  w3-tiny w3-round w3-round-xxlarge " do %>
				    <i class="fa fa-edit fa-2x" style="color: blue" aria-hidden="true" title="Edit Faculty"> </i>  
			    <% end %> 		        	
		    </td>
		    
		    <td style="width: 10px">
			    <% if department_master.active_status == false %>
			       		<%= link_to  enable_department_path(:chosen => department_master.id), :title =>"", class: "w3-btn w3-sand w3-card  w3-tiny w3-round w3-round-xxlarge ", data: { confirm: 'You are about to restore the selected department. Do you want to continue?' } do %>
						  <i class="fa fa-check fa-2x" style="color: green" aria-hidden="true" title="Restore Department"> </i>  
						<% end %> 
			       
		        <% else department_master.active_status == true %>
		           		<%= link_to  disable_department_path(:chosen => department_master.id), class: "w3-btn w3-sand w3-card  w3-tiny w3-round w3-round-xxlarge ", data: { confirm: 'You are about to delete the selected department. Do you want to continue?' } do %>
						  <i class="fa fa-trash-o fa-2x" style="color: red" aria-hidden="true" title="Delete Department"> </i>  
		                <% end %>		          
		        <% end %>	
	        </td>

	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>
<br>

<%= link_to '+', new_department_master_path, class: "w3-button w3-circle w3-light-blue w3-hover-pale-blue" %>
<%= will_paginate @department_masters,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "department_masters", :action => "index", count: params[:count], page: params[:page] }  %>
</div>


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 });
 
</script>


<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        
        // filter by faculty
        $("#faculty_name").click(function() {
            if ($("#faculty_name").is(":checked")) {
                $("#search-field").attr("placeholder", "Enter the faculty name");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
                $("#date-field").addClass("hidden");
                $("#date-field2").addClass("hidden");
                $("#search-field3").addClass("hidden")
                $("#to").addClass("hidden");
            }
        });
        
        // filter by department
        $("#department_name").click(function() {
            if ($("#department_name").is(":checked")) {
                $("#search-field").attr("placeholder", "Enter the department name");
                $("#search-field2").removeClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#date-field").addClass("hidden");
                $("#date-field2").addClass("hidden");
                $("#search-field3").addClass("hidden")
                $("#to").addClass("hidden");
            }
        });
        
       
      
        
        ////////////////////////////////////////////////////////////////////////////
        $("#location").click(function() {
            if ($("#location").is(":checked")) {
                $("#search-field").attr("placeholder", "Enter the location");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        
        
         //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").addClass("hidden");
            $("#search-field").addClass("hidden");
            $("#search-field3").removeClass("hidden");
            $("#to").removeClass("hidden");
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        $("#date-field").click(function() {
           // if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            // $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        
        ///////////////////////////////////////////////////
        $.fn.datepicker.noConflict = function() {
            $.fn.datepicker = old;
            return this;
        };
        ////////////////////////////////////////////////////
        $(function() {
            $('#date-field').datepicker({
                dateFormat : 'yy-mm-dd'
            }).val();
        });
        //////////////////////////////////////////////////////
        $(function() {
            $('#date-field2').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
        
        
        
     
        // ///////////////////////////////////////////////////
        // $.fn.datepicker.noConflict = function() {
            // $.fn.datepicker = old;
            // return this;
        // };
        // ////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
        // //////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field2').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
//         
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

app/views/department_masters/new.html.erb
<%= render 'form' %>